"""
Real K<=4 CORE sequence runner for the TUF TSTM study.
Executes P1/P2/P4/P5 scenarios against REAL python-tuf and REAL go-tuf v2
client binaries via tuf-conformance's own RepositorySimulator/ClientRunner.

Every result in the output JSON comes from an actual subprocess execution
of a real TUF client. Nothing here is fabricated or inferred.

Corrections applied after external review (see tuf_study/baseline/):
  - sequence_id is generated by the single canonical
    tstm_analysis.sequence_id() function.
  - Every step_results key is explicitly tagged with a role via
    step_role_map: the transition it is the decision for, "SETUP" for a real
    client call that is not itself a modeled security transition, or
    "INTROSPECTION" for a non-decision value that must never be folded into
    a decision trace (SEQUENCE_ID_AUDIT.md / the P5 final_delegated_role_version
    bug).
  - P1 REDESIGNED (per explicit user decision, not a unilateral call): the
    original single-step P1 ("root rotation missing old-threshold
    signature, REJECT") is DEMOTED to a documented control case
    (case_label="P1_CONTROL", oracle_properties=[] -- it does not count
    toward this study's 5 headline properties or toward C2/C3/C4 anymore),
    because tuf-conformance's own official
    test_updater_key_rotations.py::test_root_rotation
    ["1-of-1-key-rotation-fail-not-signed-with-old-key"] case already tests
    this exact single-transition scenario -- confirmed by direct source
    inspection, not assumption. The new P1 is a genuine 3-transition
    composition with no official equivalent found by inspection:
        VALID_ROTATION -> INVALID_ROTATION_REJECT -> VALID_RECOVERY
    i.e. ROOT_ROTATE_VALID, then ROOT_ROTATE_INSUF_THRESHOLD (expected
    REJECT), then ROOT_ROTATE_VALID again (expected ACCEPT). This tests
    whether a client's rejection of one bad rotation attempt corrupts its
    ability to accept a subsequent, independently legitimate rotation --
    the "reject -> recovery" composition class that _DEFAULT_REACHABLE_NEXT
    previously modeled as unreachable by treating REJECT outcomes as
    terminal, which the state-transition engine
    (tuf_study/analysis/state_engine.py) built alongside this case
    corrects.
Path parameterization: every
path below defaults to this session's actual machine layout (so this script
still runs unmodified here), but can be overridden via environment variables
for any other machine/artifact-evaluation environment:
  TUF_STUDY_EXPERIMENT_DIR  (default: C:\\Users\\yasemin.bozkurt\\tuf_experiment)
  TUF_STUDY_REPO_DIR        (default: C:\\Users\\yasemin.bozkurt\\Desktop\\new\\tuf_study)
"""
import json
import os
import sys

EXPERIMENT_DIR = os.environ.get("TUF_STUDY_EXPERIMENT_DIR", r"C:\Users\yasemin.bozkurt\tuf_experiment")
REPO_DIR = os.environ.get("TUF_STUDY_REPO_DIR", r"C:\Users\yasemin.bozkurt\Desktop\new\tuf_study")
CONFORMANCE_DIR = os.path.join(EXPERIMENT_DIR, "tuf-conformance")

sys.path.insert(0, CONFORMANCE_DIR)
sys.path.insert(0, os.path.join(REPO_DIR, "analysis"))

from tuf.api.metadata import Root, Timestamp, Snapshot, Targets, DelegatedRole, MetaFile
from tuf_conformance._internal.client_runner import ClientRunner
from tuf_conformance._internal.simulator_server import SimulatorServer

import tstm_analysis as pl

PYTUF_ENTRY = os.path.join(CONFORMANCE_DIR, "clients", "python-tuf", "run_python_tuf.bat")
GOTUF_ENTRY = os.path.join(CONFORMANCE_DIR, "clients", "go-tuf", "go-tuf.exe")
TUFJS_ENTRY = os.path.join(CONFORMANCE_DIR, "clients", "tuf-js", "run_tuf_js.bat")

# Third independent implementation added per explicit user request to
# strengthen the differential-testing dimension beyond two implementations
# (PAPER_DRAFT.md Sec.11 Future Research item (3), now executed). tuf-js is
# the JavaScript/TypeScript reference implementation used by npm's own
# supply-chain security tooling and is one of the implementations tracked by
# the official tuf-conformance results page. Built from a shallow clone of
# theupdateframework/tuf-js (main branch, this session) with a portable
# Node.js v22.13.0 (no admin rights required, same pattern as the portable
# Go install from the first round of this study).
IMPLS = {"python-tuf": PYTUF_ENTRY, "go-tuf-v2": GOTUF_ENTRY, "tuf-js": TUFJS_ENTRY}

# Real, freshly-initialized RepositorySimulator state -- identical for every
# case below, since every case calls server.new_test() (a fresh simulator)
# before doing anything else. Not a placeholder: this is what
# SimulatorServer.new_test() actually constructs (root v1, single key,
# threshold 1, timestamp/snapshot/targets v1, no delegations, valid
# expiration), per direct reading of
# tuf_conformance/_internal/simulator_server.py and repository_simulator.py
# in this pinned checkout (see ../REPRODUCIBILITY.md for the commit hash).
FRESH_INITIAL_STATE = {
    "R_v": 1, "R_K": ["root_key_0"], "R_t": 1,
    "T_v": 1, "S_v": 1, "G_v": 1,
    "D": "DELEGATION_ABSENT", "E": "EXPIRATION_VALID",
}


def manual_publish_with_signers(repo, role: str, signers: list, replace_current: bool = False) -> None:
    """Replicates RepositorySimulator.publish()'s core signing logic but with
    an explicit signer list instead of repo.signers[role]. Used to construct
    root versions signed by an explicit, controlled key set.

    replace_current=True republishes the SAME version number (does not
    increment) and REPLACES the last entry in repo.signed_mds[role] in place,
    instead of appending a new one. This is required to correctly model
    "the repo owner fixes and republishes version N" (e.g. a recovery after a
    bad signing attempt) -- TUF's root-update loop fetches root versions
    strictly sequentially via repo.signed_mds[role][version - 1] (see
    repository_simulator.py), so appending a NEW list entry instead of
    replacing would serve it as a *different, later* version, which a client
    still stuck failing to verify the earlier bad version could never reach.
    Discovered as a genuine construction bug in an early attempt at the P1
    reject->recovery sequence: appending instead of replacing made both
    clients correctly REJECT the "recovery" step, not because recovery
    itself is unsupported, but because the bad intermediate version was
    still blocking the sequential root-update chain. See
    tuf_study/baseline/ for the full writeup."""
    from tuf.api.serialization.json import JSONSerializer

    md = repo.mds[role]
    if not replace_current:
        md.signed.version += 1
    md.signatures.clear()
    for signer in signers:
        md.sign(signer, append=True)
    if role not in repo.signed_mds:
        repo.signed_mds[role] = []
    encoded = md.to_bytes(JSONSerializer())
    if replace_current and repo.signed_mds[role]:
        repo.signed_mds[role][-1] = encoded
    else:
        repo.signed_mds[role].append(encoded)
    if role not in [Root.type, Timestamp.type, Snapshot.type]:
        repo.snapshot.meta[f"{role}.json"] = MetaFile(md.signed.version, None, None)
    if role == Snapshot.type:
        repo.timestamp.snapshot_meta = MetaFile(md.signed.version, None, None)


results = []
corpus = []
server = SimulatorServer(None)


def run_case(family: str, case_label: str, oracle_properties: list[str],
             transitions_desc: list[str], step_role_map: dict[str, str],
             boundary_states: list[str], fn, control_case_note: str | None = None):
    """fn(repo, client, init_data) -> dict of {step_name: exit_code / value}.
    Executed once per implementation.

    case_label: internal unique identifier (e.g. "P1", "P1_CONTROL") used for
      test naming and for keying build_real_dataset.py's per-case tables.
      Always non-empty, always used for sequence_id hashing (so demoting a
      case to a control does not silently collide its ID with anything).
    oracle_properties: the OFFICIAL, schema-constrained list this sequence
      counts toward (subset of P1-P5). Empty for a control/overlap case that
      should not contribute to this study's coverage claims.
    step_role_map: maps every key `fn` can return to one of:
      - a transition_type string in `transitions_desc` (this step IS the
        observed decision for that modeled transition),
      - "SETUP" (a real client call, not itself a modeled transition),
      - "INTROSPECTION" (not a decision at all -- e.g. a version number;
        must never appear in a decision trace).
    """
    cid = pl.sequence_id(family, [case_label], transitions_desc)
    entry = {
        "sequence_id": cid, "family": family, "case_label": case_label, "origin": "TSTM_GENERATED",
        "transitions": [{"step_index": i, "transition_type": t, "parameters": {}, "counts_toward_k": True}
                         for i, t in enumerate(transitions_desc)],
        "length": len(transitions_desc), "oracle_properties": oracle_properties,
        "initial_state": FRESH_INITIAL_STATE,
        "step_role_map": step_role_map,
        "boundary_states": boundary_states,
    }
    if control_case_note:
        entry["control_case_note"] = control_case_note
    corpus.append(entry)
    for impl_name, entry_path in IMPLS.items():
        test_name = f"{family}_{case_label}_{impl_name}".replace(" ", "_")
        client = ClientRunner(entry_path, server, test_name)
        init_data, repo = server.new_test(test_name)
        try:
            step_results = fn(repo, client, init_data)
        except Exception as e:
            step_results = {"EXCEPTION": str(e)}
        results.append({
            "sequence_id": cid, "implementation": impl_name,
            "family": family, "case_label": case_label,
            "step_results": step_results,
        })
        print(f"[{family}/{case_label}] {impl_name}: {step_results}")


# ---------------------------------------------------------------------
# P2 -- skipped root version must be REJECTED (root_v1 -> root_v3, no v2)
# ---------------------------------------------------------------------
def p2_case(repo, client, init_data):
    assert client.init_client(init_data) == 0
    r0 = client.refresh(init_data)  # SETUP: initial trust-bootstrap refresh at v1
    # Force a version SKIP: bump root version by 2 in one publish (v1->v3).
    # There is no intermediate valid v1->v2 rotation in this case at all.
    repo.root.version += 1
    repo.rotate_keys(Root.type)
    repo.publish([Root.type], verify_version=False)  # v1 -> v3 directly
    r1 = client.refresh(init_data)  # decision for ROOT_ROTATE_SKIP
    return {"baseline_refresh": r0, "refresh_after_skip_v1_to_v3": r1}


run_case(
    "F1", "P2", ["P2"], ["ROOT_ROTATE_SKIP"],
    step_role_map={"baseline_refresh": "SETUP", "refresh_after_skip_v1_to_v3": "ROOT_ROTATE_SKIP"},
    boundary_states=["VERSION_SKIPPED_NEXT"],
    fn=p2_case,
)


# ---------------------------------------------------------------------
# P4 -- metadata signed only by a since-removed root key must be REJECTED
# ---------------------------------------------------------------------
def p4_case(repo, client, init_data):
    """P4: after a GENUINELY VALID root rotation (dual-signed by both the
    old-trusted threshold AND the new threshold, per spec Sec.5.3.4), a
    later root version signed ONLY by the now-removed old key must be
    rejected."""
    assert client.init_client(init_data) == 0
    r0 = client.refresh(init_data)  # SETUP: trust root v1

    old_signers = dict(repo.signers[Root.type])  # capture BEFORE rotation

    # Genuinely valid rotation: sign v2 with BOTH old signer(s) AND new
    # signer(s), satisfying the dual-threshold requirement, matching the
    # pattern proven in tuf-conformance's own test_root_rotation.
    new_signer = repo.new_signer()
    repo.root.add_key(new_signer.public_key, Root.type)
    repo.root.roles[Root.type].keyids.clear()
    repo.root.add_key(new_signer.public_key, Root.type)  # new key is now sole authorized key for v2
    repo.signers[Root.type] = {new_signer.public_key.keyid: new_signer}
    manual_publish_with_signers(
        repo, Root.type, list(old_signers.values()) + [new_signer]
    )  # v2 signed by BOTH v1-threshold key(s) AND v2-threshold key -> genuinely valid
    r1 = client.refresh(init_data)  # decision for ROOT_ROTATE_VALID

    # Now attempt root v3 signed ONLY by the OLD (v1, now-removed) key
    manual_publish_with_signers(repo, Root.type, list(old_signers.values()))
    r2 = client.refresh(init_data)  # decision for METADATA_BY_REMOVED_KEY
    return {
        "baseline_refresh_v1": r0,
        "refresh_after_genuinely_valid_rotation_v2": r1,
        "refresh_v3_signed_only_by_removed_v1_key": r2,
    }


run_case(
    "F5", "P4", ["P4"], ["ROOT_ROTATE_VALID", "METADATA_BY_REMOVED_KEY"],
    step_role_map={
        "baseline_refresh_v1": "SETUP",
        "refresh_after_genuinely_valid_rotation_v2": "ROOT_ROTATE_VALID",
        "refresh_v3_signed_only_by_removed_v1_key": "METADATA_BY_REMOVED_KEY",
    },
    boundary_states=["KEY_REMOVED", "KEY_FULL_REPLACEMENT"],
    fn=p4_case,
)


# ---------------------------------------------------------------------
# P1_CONTROL -- DEMOTED from novel P1 (see module docstring). Kept and still
# executed for real, because it is real, already-verified data and dropping
# it would just be discarding evidence -- but excluded from
# oracle_properties / C2-C4, and documented as overlapping an official case.
# ---------------------------------------------------------------------
def p1_control_case(repo, client, init_data):
    assert client.init_client(init_data) == 0
    r0 = client.refresh(init_data)  # SETUP: trust root v1 (key K1, threshold 1)

    old_signers = list(repo.signers[Root.type].values())
    new_signer = repo.new_signer()
    repo.root.roles[Root.type].keyids.clear()
    repo.root.add_key(new_signer.public_key, Root.type)  # v2 authorizes only K2

    # Sign v2 ONLY with the new key K2 -- does NOT satisfy v1's threshold
    # (which requires a signature from K1).
    manual_publish_with_signers(repo, Root.type, [new_signer])
    r1 = client.refresh(init_data)  # decision for ROOT_ROTATE_INSUF_THRESHOLD
    return {
        "baseline_refresh_v1": r0,
        "refresh_v2_signed_only_by_new_key_missing_old_threshold": r1,
    }


run_case(
    "F1", "P1_CONTROL", [], ["ROOT_ROTATE_INSUF_THRESHOLD"],
    step_role_map={
        "baseline_refresh_v1": "SETUP",
        "refresh_v2_signed_only_by_new_key_missing_old_threshold": "ROOT_ROTATE_INSUF_THRESHOLD",
    },
    boundary_states=["THRESHOLD_BELOW"],
    fn=p1_control_case,
    control_case_note=(
        "Overlaps tuf-conformance's own official "
        "test_updater_key_rotations.py::test_root_rotation"
        "[1-of-1-key-rotation-fail-not-signed-with-old-key], confirmed by "
        "direct source inspection (see tuf_study/baseline/). Kept as a real, "
        "executed control/regression case, not claimed as a novel TSTM "
        "contribution -- excluded from oracle_properties and from C2-C4."
    ),
)


# ---------------------------------------------------------------------
# P1 (REDESIGNED) -- reject -> recovery composition:
#   VALID_ROTATION -> INVALID_ROTATION_REJECT -> VALID_RECOVERY
# Tests whether a client's correct rejection of one invalid rotation attempt
# corrupts its ability to accept a SUBSEQUENT, independently valid rotation.
# No official tuf-conformance case was found (by direct source inspection of
# test_updater_key_rotations.py's root_rotation_cases, which are independent
# parametrized scenarios, not sequenced attack-then-recovery chains) that
# exercises this composition.
# ---------------------------------------------------------------------
def p1_case(repo, client, init_data):
    assert client.init_client(init_data) == 0
    r0 = client.refresh(init_data)  # SETUP: trust root v1 (key K1, threshold 1)

    k1_signers = dict(repo.signers[Root.type])  # {K1}, v1's threshold

    # Step 1 -- VALID_ROTATION: root v1 -> v2, dual-signed (K1 + new K2),
    # satisfying Sec.5.3.4's dual-threshold requirement (same proven pattern
    # as P4's first step).
    k2_signer = repo.new_signer()
    repo.root.add_key(k2_signer.public_key, Root.type)
    repo.root.roles[Root.type].keyids.clear()
    repo.root.add_key(k2_signer.public_key, Root.type)
    repo.signers[Root.type] = {k2_signer.public_key.keyid: k2_signer}
    manual_publish_with_signers(repo, Root.type, list(k1_signers.values()) + [k2_signer])
    r1 = client.refresh(init_data)  # decision for ROOT_ROTATE_VALID (step 0), expect ACCEPT

    k2_signers = dict(repo.signers[Root.type])  # {K2}, now v2's current threshold

    # Step 2 -- INVALID_ROTATION_REJECT: attempt root v2 -> vNext signed ONLY
    # by a brand-new K3, missing v2's required K2 signature. Same class of
    # violation as P1_CONTROL/the official case, but now composed AFTER a
    # real prior rotation rather than as an isolated first-ever rotation.
    k3_signer = repo.new_signer()
    repo.root.roles[Root.type].keyids.clear()
    repo.root.add_key(k3_signer.public_key, Root.type)
    manual_publish_with_signers(repo, Root.type, [k3_signer])  # only K3 -- missing K2
    r2 = client.refresh(init_data)  # decision for ROOT_ROTATE_INSUF_THRESHOLD (step 1), expect REJECT

    # Step 3 -- VALID_RECOVERY: the repo owner fixes and REPUBLISHES THE SAME
    # version (not a new, later one -- TUF's root-update loop is strictly
    # sequential, so a client stuck failing to verify version N could never
    # skip ahead to N+1; see manual_publish_with_signers' replace_current
    # docstring for the construction bug this fixes), this time correctly
    # dual-signed by K2 (v2's current threshold, unaffected by the rejected
    # attempt) AND K3 (the version's own declared key). If the client's
    # rejection of step 2 corrupted its trusted state, this legitimate
    # rotation would also be rejected; if the client correctly treated the
    # bad attempt as a no-op, this must be ACCEPTed.
    manual_publish_with_signers(repo, Root.type, list(k2_signers.values()) + [k3_signer], replace_current=True)
    r3 = client.refresh(init_data)  # decision for ROOT_ROTATE_VALID (step 2), expect ACCEPT
    return {
        "baseline_refresh_v1": r0,
        "refresh_after_valid_rotation_v1_to_v2": r1,
        "refresh_after_insuf_threshold_attempt": r2,
        "refresh_after_valid_recovery_rotation": r3,
    }


run_case(
    "F1", "P1", ["P1"],
    ["ROOT_ROTATE_VALID", "ROOT_ROTATE_INSUF_THRESHOLD", "ROOT_ROTATE_VALID"],
    step_role_map={
        "baseline_refresh_v1": "SETUP",
        "refresh_after_valid_rotation_v1_to_v2": "ROOT_ROTATE_VALID",
        "refresh_after_insuf_threshold_attempt": "ROOT_ROTATE_INSUF_THRESHOLD",
        "refresh_after_valid_recovery_rotation": "ROOT_ROTATE_VALID",
    },
    boundary_states=["THRESHOLD_BELOW", "THRESHOLD_EXACT", "KEY_FULL_REPLACEMENT"],
    fn=p1_case,
)


# ---------------------------------------------------------------------
# P5 -- stale delegated metadata must be REJECTED after delegation removal
# ---------------------------------------------------------------------
def p5_case(repo, client, init_data):
    assert client.init_client(init_data) == 0
    role = DelegatedRole("delegated", [], 1, False, ["delegatedpath/*"])
    delegated_targets = Targets(expires=repo.safe_expiry)
    repo.add_delegation(Targets.type, role, delegated_targets)
    repo.add_artifact("delegated", b"real-target-content-for-p5-test", "delegatedpath/foo")
    repo.publish(["delegated", Targets.type])
    repo.publish([Snapshot.type, Timestamp.type])  # required: makes "delegated.json" actually visible to client
    r0 = client.refresh(init_data)  # decision for DELEGATION_CREATE (first time it's visible to the client)
    r0b = client.download_target(init_data, "delegatedpath/foo")  # SETUP: confirms the delegation actually works

    # Remove the delegation entirely (not just from snapshot -- full authorization removal)
    del repo.targets.delegations.roles["delegated"]
    repo.publish([Targets.type, Snapshot.type, Timestamp.type])
    r1 = client.refresh(init_data)  # decision for DELEGATION_REMOVE
    r2 = client.download_target(init_data, "delegatedpath/foo")  # decision for DELEGATED_REPLAY_AFTER_REMOVAL
    final_version = client.version("delegated")  # INTROSPECTION only -- a version number, NOT a decision
    return {
        "refresh_with_delegation": r0,
        "download_via_delegation": r0b,
        "refresh_after_delegation_removed": r1,
        "download_after_delegation_removed": r2,
        "final_delegated_role_version": final_version,
    }


run_case(
    "F4", "P5", ["P5"],
    ["DELEGATION_CREATE", "DELEGATION_REMOVE", "DELEGATED_REPLAY_AFTER_REMOVAL"],
    step_role_map={
        "refresh_with_delegation": "DELEGATION_CREATE",
        "download_via_delegation": "SETUP",
        "refresh_after_delegation_removed": "DELEGATION_REMOVE",
        "download_after_delegation_removed": "DELEGATED_REPLAY_AFTER_REMOVAL",
        "final_delegated_role_version": "INTROSPECTION",
    },
    boundary_states=["DELEGATION_ACTIVE", "DELEGATION_REMOVED"],
    fn=p5_case,
)


# ---------------------------------------------------------------------
server.server_close()

with open(os.path.join(REPO_DIR, "example_data", "REAL_sequence_corpus.json"), "w") as f:
    json.dump(corpus, f, indent=2)
with open(os.path.join(REPO_DIR, "example_data", "REAL_raw_results.json"), "w") as f:
    json.dump(results, f, indent=2, default=str)

print("\n\nDONE. Wrote REAL_sequence_corpus.json and REAL_raw_results.json")
print("(this run's stdout, including every subprocess's own printed output "
      "since ClientRunner does not redirect its subprocess's stdio, is "
      "captured in full if this script was invoked with output redirected "
      "to a file -- see tuf_study/example_data/raw_logs/ for the persisted copy)")
